application: yt-mlb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: mlb.html
  upload: mlb.html

- url: /yt-api
  static_files: yt-api.html
  upload: yt-api.html

- url: /launch
  static_files: launch.html
  upload: launch.html
  
- url: /ss
  static_files: ss.html
  upload: ss.html



- url: /css
  static_dir: css
- url: /js
  static_dir: js


  
  
  